blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions / 質問やディスカッション
    url: https://github.com/dot-1245/go-music-tui/discussions
    about: Please ask questions or start discussions here. (質問や雑談、ちょっとした相談はこちらへどうぞ！)
